#!/bin/bash

# Prevent sudo timeout
sudo -v # ask for sudo password up-front
while true; do
  # Update user's timestamp without running a command
  sudo -nv; sleep 1m
  # Exit when the parent process is not running any more. In fact this loop
  # would be killed anyway after being an orphan(when the parent process
  # exits). But this ensures that and probably exit sooner.
  kill -0 $$ 2>/dev/null || exit
done &

rustup self update
rustup update
gpg --keyserver pool.sks-keyservers.net --recv-keys D1483FA6C3C07136
sudo pacman -Syy --noconfirm
sudo pacman -Su --noconfirm
yaourt -Syua --noconfirm
sudo pacman -Sc --noconfirm
